#!/bin/sh
#
# Restart the S4 connector if an interface was stopped.
#  See https://forge.univention.org/bugzilla/show_bug.cgi?id=30119
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2013-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

[ -x /etc/init.d/univention-s4-connector ] || exit 0

. /etc/network/ucs-network-tools
ucs_ignore_interface

invoke-rc.d univention-s4-connector crestart

exit 0
