#!/bin/sh
#
# Univention Directory Manager Modules
#  postrm script
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

case "$1" in
	"remove")
		## unload the listener module
		systemctl try-restart univention-directory-listener
		;;
	"purge")
		;;
	*)
		;;
esac

exit 0
