#!/bin/sh
#
# Univention Fetchmail
#  preinst script
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2013-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#


if [ "$1" = "install" ]; then
	test -e /usr/lib/univention-install/93univention-fetchmail-uninstall.uinst && rm /usr/lib/univention-install/93univention-fetchmail-uninstall.uinst
fi

exit 0
