#!/bin/sh
#
# Univention Management Console module passwordchange
#  postinst script for the debian package
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

# register JavaScript hook
univention-config-registry set "umc/web/hooks/univention-management-console-module-passwordchange?passwordchange"

exit 0
