#!/bin/sh

# SPDX-FileCopyrightText: 2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

set -e -u

exec "${0%/*}/ht" --ignore-stdin --pretty=all \
    POST "$APTLY/publish/$CI_COMMIT_REF_SLUG" \
    'SourceKind=local' \
    "Sources:=[{\"Name\":\"$CI_COMMIT_REF_SLUG\",\"Component\":\"main\"}]" \
    'Distribution=git' \
    'Label=Univention Corporate Server' \
    'Origin=Univention' \
    'ForceOverwrite:=true' \
    'AcquireByHash:=true' \
    'Architectures:=["amd64","source"]'
