#!/bin/sh
#
# Univention Updater
#  System setup appliance hook script
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2013-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

# Identify this system as appliance
if [ -z "$(ucr get updater/identify)" ]; then
	ucr set updater/identify="UCS (appliance)"
fi

exit 0

