#!/bin/sh
#
# Univention Management Console Web Server
#  preinst script for the debian package
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2023-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

if [ "$1" = "upgrade" ] && dpkg --compare-versions "$2" lt-nl 12.0.21-2; then
	systemctl stop univention-management-console-web-server
fi

exit 0
