#!/bin/sh
#
# Univention Updater
#  update check script
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2010-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

if [ "$1" = "--silent" ] ; then
	exec > /dev/null 2> /dev/null
fi

# univention-upgrade can handle UCR variable update/available on its own
univention-upgrade --check --setucr

exit 0
