#!/bin/sh
#
# Update status file of Univention System Setup
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2016-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

echo -n '"appliance-hooks"' > /var/www/ucs_setup_process_status.json

exit 0
