#!/bin/sh
#
# Univention AD Connector
#  Start script for the AD Conenctor
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

umask 027
/usr/bin/python3 -W ignore -m univention.connector.ad.main "$@"
