#! /bin/sh
#
# Univention SSL
#  postrm script
#
# SPDX-FileCopyrightText: 2004-2018 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

set -e

if [ "$1" = "purge" ]; then
	rm -rf /etc/univention/ssl;
fi

#DEBHELPER#

