#!/bin/sh
# SPDX-FileCopyrightText: 2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

case "$2,$3" in
	,|template,)
		git diff --cached --name-only -r | while read -r f
		do
			case "$f" in
			debian/changelog|*/debian/changelog)
				python3 ${0%/*}/conventional-commit-message debian-changelog "$f" >"$1.$$"
				;;
			doc/errata/staging/*.yaml|doc/errata/published/*.yaml)
				python3 ${0%/*}/conventional-commit-message errata-advisory "$f" >"$1.$$"
				git log -1 --pretty=format:'%n# Fixes: %H' -- "$f" >>"$1.$$"
				;;
			*) continue ;;
			esac
			cat "$1" >>"$1.$$"
			mv "$1.$$" "$1"
		done
	;;
  *) ;;
esac
