#!/bin/bash
#
# Univention Self Service
#  prerm file for the debian package
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2015-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

case "$1" in
	remove)
		a2dissite univention-self-service
		univention-config-registry unset "umc/web/hooks/univention-self-service"
	;;
esac

exit 0
