#!/bin/sh
#
# Univention S4 Connector
#  Start script for the S4 Conenctor
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

umask 027
/usr/bin/python3 -W ignore -m univention.s4connector.s4.main "$@"
