#!/bin/sh
#
# Remove "no-ldap" status file of Univention System Setup
# (created by /usr/lib/univention-system-setup/scripts/setup-join.sh)
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2021-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

rm -f /var/run/univention-system-setup.ldap

exit 0
