#!/bin/sh
#
# Restart the Directory Notifier and Listener
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2013-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

exec systemctl try-restart univention-directory-notifier univention-directory-listener
