#!/bin/sh
#
# Restart amavis
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2013-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

if [ -x /etc/init.d/amavis ]; then
	invoke-rc.d amavis restart
fi

exit 0
