#!/bin/sh
#
# Remove univention-system-setup-boot package
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2014-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

# Remove univention-system-setup-boot after successful run

apt-mark auto univention-management-console-web-server univention-management-console-module-setup
dpkg -r univention-system-setup-boot
