#!/bin/sh -e
@%@UCRWARNING=# @%@
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2015-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only
#

[ -x /usr/sbin/rndc ] || exit 0
systemctl is-active --quiet named.service || exit 0

# Always reload, even for loopback
service named reload

exit 0
