#!/bin/sh
#
# Univention AD Connector
#  prerm script of the ad connector package
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only


if [ "$1" = "remove" ]; then
    test -x /etc/init.d/univention-ad-connector && /etc/init.d/univention-ad-connector stop
fi

#DEBHELPER#

exit 0
