#!/bin/sh
#
# postrm script
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2019-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

systemctl try-restart univention-directory-listener

if [ "$1" = "remove" ]; then
	univention-config-registry unset admin/diary/backend
	invoke-rc.d rsyslog restart
fi

exit 0
