#!/bin/sh

@%@UCRWARNING=# @%@

#
# Univention Spamassassin
#  learn Spam/Ham from global mail spam folder
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

PATH=/usr/sbin:/usr/bin:/sbin:/bin

@!@
if configRegistry.is_true('mail/antispam/learndaily', False):
    print('/usr/sbin/univention-sa-learn >> /var/log/univention/spamassassin-learn.log')
@!@

