#!/bin/sh
#
# Univention Postgresql
#  preinst
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

if [ "$1" = install ] && [ -z "$2" ] && [ -e /etc/univention/templates/removed/univention-postgresql.info ]
then
	rm -f /etc/univention/templates/removed/univention-postgresql.info
fi

#DEBHELPER#

exit 0
