#!/bin/sh
#
# Univention Apache
#  prerm script for the debian package
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2016-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

if [ "$1" = "remove" ]; then
	a2disconf ucs
	a2dissite default-ssl.conf || true
	a2dissite 000-default.conf || true
	service apache2 reload
fi

exit 0
